In [2]:
import numpy as np

In [3]:
a = np.arange(6)

In [4]:
type(a)

numpy.ndarray

In [5]:
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [7]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [8]:
a.shape

(2, 3)

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])

In [10]:
a

array([1, 2, 3, 4, 5, 6])

In [11]:
print(a[0])

1


In [12]:
a[0] = 10

In [13]:
a

array([10,  2,  3,  4,  5,  6])

In [14]:
a[:3]

array([10,  2,  3])

In [15]:
b = a[3:]

In [16]:
b

array([4, 5, 6])

In [17]:
b[0] = 40

In [18]:
a

array([10,  2,  3, 40,  5,  6])

In [19]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [20]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
a[1, 3]

np.int64(8)

In [22]:
a.ndim

2

In [23]:
a.shape

(3, 4)

In [24]:
len(a.shape) == a.ndim

True

In [25]:
a.size

12

In [26]:
import math

In [27]:
a.size == math.prod(a.shape)

True

In [28]:
a.dtype

dtype('int64')

In [29]:
np.zeros(2)

array([0., 0.])

In [30]:
np.ones(2)

array([1., 1.])

In [32]:
np.empty(2) 

array([1., 1.])

In [33]:
np.arange(4)

array([0, 1, 2, 3])

In [34]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [35]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [37]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [38]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [40]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [42]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [44]:
array_example.ndim

3

In [45]:
array_example.size

24

In [46]:
array_example.shape

(3, 2, 4)

In [47]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [48]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [49]:
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [50]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [51]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [52]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [53]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [54]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [55]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [56]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [58]:
data = np.array([1, 2, 3])

data[1]

np.int64(2)

In [59]:
data[0:2]

array([1, 2])

In [60]:
data[1:]

array([2, 3])

In [61]:
data[-2:]

array([2, 3])

In [62]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [63]:
print(a[a < 5])

[1 2 3 4]


In [64]:
five_up = (a >= 5)

In [65]:
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [66]:
divisible_by_2 = a[a%2==0]

In [67]:
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [68]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [69]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [70]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [71]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [72]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [73]:
print(a[b])

[1 2 3 4]


In [74]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [75]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [77]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [78]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [79]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [80]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [81]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [82]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [83]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [85]:
b1 = a[0, :]
b1

array([99,  2,  3,  4])

In [86]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [87]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
b2 = a.copy()

In [89]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [90]:
data - ones

array([0, 1])

In [91]:
data * data

array([1, 4])

In [92]:
data / data

array([1., 1.])

In [93]:
a = np.array([1, 2, 3, 4])

In [94]:
a.sum()

np.int64(10)

In [95]:
b = np.array([[1, 1], [2, 2]])

In [96]:
b.sum(axis=0)

array([3, 3])

In [97]:
b.sum(axis=1)

array([2, 4])

In [98]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [99]:
data = np.array([1, 2, 3])
data.max()

np.int64(3)

In [100]:
data.min()

np.int64(1)

In [101]:
data.sum()

np.int64(6)

In [102]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [103]:
a.sum()

np.float64(4.8595784)

In [104]:
a.min()

np.float64(0.05093587)

In [105]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [106]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
data[0, 1]

np.int64(2)

In [108]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [109]:
data[0:2, 0]

array([1, 3])

In [110]:
data.max()

np.int64(6)

In [114]:
data.min()

np.int64(1)

In [113]:
data.sum()

np.int64(21)

In [115]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [116]:
data.max(axis=0)

array([5, 6])

In [117]:
data.max(axis=1)

array([2, 5, 6])

In [119]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [120]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [121]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [122]:
np.ones(3)

array([1., 1., 1.])

In [123]:
np.zeros(3)

array([0., 0., 0.])

In [124]:
rng = np.random.default_rng()
rng.random(3) 

array([0.36756543, 0.46155296, 0.98928557])

In [125]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [126]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [127]:
rng.random((3, 2))

array([[0.22012405, 0.99910122],
       [0.05484242, 0.62945643],
       [0.92959319, 0.69691397]])

In [128]:
rng.integers(5, size=(2, 4))

array([[4, 1, 3, 2],
       [4, 2, 2, 0]])

In [129]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [130]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [131]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [132]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [133]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [134]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [135]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [136]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [137]:
print(indices)

[0 1 2]


In [138]:
print(occurrence_count)

[2 1 1]


In [139]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [141]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [142]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [143]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [144]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [145]:
reversed_arr = np.flip(arr)

In [146]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [147]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [148]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [149]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [150]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [151]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [152]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [153]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [154]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [155]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [156]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [158]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [159]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
